#!/bin/bash

# install vimrc
if [ "$OS" != 'Windows_NT' ]; then
    if [ -f ~/.vimrc ]; then
        echo 'Skipped installing vimrc because ~/.vimrc already exists'
    else
        if ! ln -s ~/.vim/vimrc ~/.vimrc; then
            echo "Couldn't link ~/.vimrc to ~/.vim/vimrc"
        fi
    fi
else
    if [ -f ~/_vimrc ]; then
        echo 'Skipped installing vimrc because ~/_vimrc already exists'
    else
        if ! ( echo 'set runtimepath+=~/.vim/' > ~/_vimrc &&
               echo 'source ~/.vim/vimrc' >> ~/_vimrc ) ; then
            echo "Couldn't create thunk to ~/.vimrc in ~/_vimrc"
        fi
    fi
fi
